"""Canonical meteorological region registry for the VayuDRISHTI domain.

Single source of truth shared by the synthetic grid generator, the historical
verification archive builder and the inference engine. Keeping one registry
means the demo grid, the training archive and the climatology all describe the
same 20 Indian met-regions with consistent physics.

Field groups
------------
identity      : grid_id, name, subdivision, lat, lon, climate_type
climatology   : baseline_slp, base_pwat  (typical state of the region)
error physics : param_gain, chaos_gain, orographic_gain
published     : published_bust_freq_pct, worst_lead_day, peak_event,
                published_mae_mm  (NCMRWF-style verification summary that the
                archive generator is validated against)

Error physics
-------------
param_gain     Scale of the *model* error component. Short-lead busts are
               dominated by parameterisation failure (convective schemes,
               orographic resolution, boundary-layer flux), so this drives
               Day 1-3 behaviour.
chaos_gain     Scale of the *predictability* component. Grows with lead time
               through the Lyapunov exponent and through ensemble
               disagreement, so this drives Day 5-10 behaviour.
orographic_gain  Extra multiplicative forcing from unresolved relief, which
               both degrades the physics and seeds phase errors downstream.
"""
from typing import Any, Dict, List

from app.core.config import settings

REGIONS: List[Dict[str, Any]] = [
    {
        "grid_id": "IND-NW-01",
        "name": "Kashmir & Pir Panjal Ridge",
        "subdivision": "Western Himalayas",
        "lat": 34.08,
        "lon": 74.80,
        "climate_type": "Alpine / Orographic",
        "baseline_slp": 1016.0,
        "base_pwat": 24.0,
        "param_gain": 11.0,
        "chaos_gain": 9.0,
        "orographic_gain": 0.80,
        "published_bust_freq_pct": 12.4,
        "worst_lead_day": 6,
        "peak_event": "Western Disturbance",
        "published_mae_mm": 18.2,
    },
    {
        "grid_id": "IND-NW-02",
        "name": "Northern Punjab Plains (Amritsar)",
        "subdivision": "North-West Plains",
        "lat": 31.63,
        "lon": 74.87,
        "climate_type": "Continental Semi-Arid",
        "baseline_slp": 1012.0,
        "base_pwat": 32.0,
        "param_gain": 8.0,
        "chaos_gain": 10.0,
        "orographic_gain": 0.30,
        "published_bust_freq_pct": 9.8,
        "worst_lead_day": 7,
        "peak_event": "Western Disturbance",
        "published_mae_mm": 14.6,
    },
    {
        "grid_id": "IND-NC-03",
        "name": "Indo-Gangetic Capital Zone (Delhi NCR)",
        "subdivision": "Upper Gangetic Basin",
        "lat": 28.61,
        "lon": 77.20,
        "climate_type": "Subtropical High-Density",
        "baseline_slp": 1009.5,
        "base_pwat": 42.0,
        "param_gain": 10.0,
        "chaos_gain": 10.5,
        "orographic_gain": 0.35,
        "published_bust_freq_pct": 14.1,
        "worst_lead_day": 5,
        "peak_event": "Monsoon Active/Break Phase",
        "published_mae_mm": 22.3,
    },
    {
        "grid_id": "IND-W-04",
        "name": "Thar Desert Basin (Barmer / Jodhpur)",
        "subdivision": "Western Dry Zone",
        "lat": 26.28,
        "lon": 71.50,
        "climate_type": "Hyper-Arid Thermal",
        "baseline_slp": 1004.0,
        "base_pwat": 22.0,
        "param_gain": 6.5,
        "chaos_gain": 8.5,
        "orographic_gain": 0.15,
        "published_bust_freq_pct": 8.2,
        "worst_lead_day": 8,
        "peak_event": "Heat Wave",
        "published_mae_mm": 11.4,
    },
    {
        "grid_id": "IND-W-05",
        "name": "Gulf of Khambhat / Rann of Kutch",
        "subdivision": "Saurashtra & Kutch",
        "lat": 23.02,
        "lon": 70.80,
        "climate_type": "Coastal Arid-Marine",
        "baseline_slp": 1007.0,
        "base_pwat": 48.0,
        "param_gain": 7.0,
        "chaos_gain": 8.0,
        "orographic_gain": 0.15,
        "published_bust_freq_pct": 16.7,
        "worst_lead_day": 4,
        "peak_event": "Cyclonic System (ARB)",
        "published_mae_mm": 31.8,
    },
    {
        "grid_id": "IND-C-06",
        "name": "Malwa Plateau & Narmada Valley (Bhopal)",
        "subdivision": "Central Highlands",
        "lat": 23.25,
        "lon": 77.41,
        "climate_type": "Tropical Continental",
        "baseline_slp": 1008.0,
        "base_pwat": 46.0,
        "param_gain": 8.5,
        "chaos_gain": 8.0,
        "orographic_gain": 0.30,
        "published_bust_freq_pct": 18.3,
        "worst_lead_day": 4,
        "peak_event": "Monsoon Depression",
        "published_mae_mm": 28.5,
    },
    {
        "grid_id": "IND-C-07",
        "name": "Vidarbha Dryline Sector (Nagpur)",
        "subdivision": "East Central Deccan",
        "lat": 21.14,
        "lon": 79.08,
        "climate_type": "Tropical Semi-Arid Convective",
        "baseline_slp": 1007.5,
        "base_pwat": 44.0,
        "param_gain": 9.5,
        "chaos_gain": 9.5,
        "orographic_gain": 0.25,
        "published_bust_freq_pct": 22.1,
        "worst_lead_day": 3,
        "peak_event": "Heat Wave / Dryline",
        "published_mae_mm": 19.7,
    },
    {
        "grid_id": "IND-E-08",
        "name": "Middle Gangetic Trough (Patna)",
        "subdivision": "Bihar Plains",
        "lat": 25.59,
        "lon": 85.13,
        "climate_type": "Humid Subtropical Fluvial",
        "baseline_slp": 1006.0,
        "base_pwat": 54.0,
        "param_gain": 10.5,
        "chaos_gain": 10.0,
        "orographic_gain": 0.35,
        "published_bust_freq_pct": 19.4,
        "worst_lead_day": 4,
        "peak_event": "Monsoon Depression",
        "published_mae_mm": 34.1,
    },
    {
        "grid_id": "IND-E-09",
        "name": "Bengal Deltaic Estuary (Kolkata)",
        "subdivision": "Gangetic West Bengal",
        "lat": 22.57,
        "lon": 88.36,
        "climate_type": "Tropical Wet-and-Dry Coastal",
        "baseline_slp": 1005.0,
        "base_pwat": 58.0,
        "param_gain": 11.5,
        "chaos_gain": 11.5,
        "orographic_gain": 0.40,
        "published_bust_freq_pct": 24.8,
        "worst_lead_day": 3,
        "peak_event": "Monsoon Depression / BoB Low",
        "published_mae_mm": 42.6,
    },
    {
        "grid_id": "IND-NE-10",
        "name": "Brahmaputra Valley (Guwahati)",
        "subdivision": "Assam Valley",
        "lat": 26.14,
        "lon": 91.73,
        "climate_type": "Subtropical Valley-Trapped",
        "baseline_slp": 1007.8,
        "base_pwat": 62.0,
        "param_gain": 12.5,
        "chaos_gain": 12.0,
        "orographic_gain": 0.55,
        "published_bust_freq_pct": 28.5,
        "worst_lead_day": 3,
        "peak_event": "Orographic Heavy Rainfall",
        "published_mae_mm": 58.3,
    },
    {
        "grid_id": "IND-NE-11",
        "name": "Meghalaya Escarpment (Cherrapunji / Shillong)",
        "subdivision": "North Eastern Highlands",
        "lat": 25.30,
        "lon": 91.70,
        "climate_type": "Extreme Orographic Hyper-Pluvial",
        "baseline_slp": 1006.2,
        "base_pwat": 68.0,
        "param_gain": 15.0,
        "chaos_gain": 13.5,
        "orographic_gain": 1.05,
        "published_bust_freq_pct": 34.2,
        "worst_lead_day": 2,
        "peak_event": "Orographic Extreme Rainfall",
        "published_mae_mm": 72.1,
    },
    {
        "grid_id": "IND-W-12",
        "name": "Northern Konkan Marine Basin (Mumbai Offshore)",
        "subdivision": "Konkan Maritime",
        "lat": 18.92,
        "lon": 72.83,
        "climate_type": "Tropical Marine High-Flux",
        "baseline_slp": 1006.5,
        "base_pwat": 60.0,
        "param_gain": 12.0,
        "chaos_gain": 11.0,
        "orographic_gain": 0.60,
        "published_bust_freq_pct": 21.6,
        "worst_lead_day": 3,
        "peak_event": "Cyclonic System (ARB)",
        "published_mae_mm": 38.4,
    },
    {
        "grid_id": "IND-SW-13",
        "name": "Malabar Ridge & Ghats (Kochi / Idukki)",
        "subdivision": "Kerala Coastal Ghats",
        "lat": 9.93,
        "lon": 76.26,
        "climate_type": "Tropical Monsoon Rainforest",
        "baseline_slp": 1009.0,
        "base_pwat": 64.0,
        "param_gain": 13.5,
        "chaos_gain": 11.5,
        "orographic_gain": 0.95,
        "published_bust_freq_pct": 26.3,
        "worst_lead_day": 2,
        "peak_event": "Active Monsoon / Southwest Surge",
        "published_mae_mm": 48.7,
    },
    {
        "grid_id": "IND-S-14",
        "name": "South Deccan Interior (Bengaluru)",
        "subdivision": "South Interior Karnataka",
        "lat": 12.97,
        "lon": 77.59,
        "climate_type": "Semi-Arid Plateau Elevated",
        "baseline_slp": 1011.0,
        "base_pwat": 40.0,
        "param_gain": 8.0,
        "chaos_gain": 9.0,
        "orographic_gain": 0.35,
        "published_bust_freq_pct": 11.2,
        "worst_lead_day": 6,
        "peak_event": "Monsoon Active/Break Phase",
        "published_mae_mm": 16.8,
    },
    {
        "grid_id": "IND-SE-15",
        "name": "Coromandel Coastal Arc (Chennai)",
        "subdivision": "Tamil Nadu Coastal",
        "lat": 13.08,
        "lon": 80.27,
        "climate_type": "Tropical Marine Maritime",
        "baseline_slp": 1008.2,
        "base_pwat": 56.0,
        "param_gain": 11.0,
        "chaos_gain": 10.5,
        "orographic_gain": 0.45,
        "published_bust_freq_pct": 17.9,
        "worst_lead_day": 4,
        "peak_event": "Northeast Monsoon Cyclone",
        "published_mae_mm": 29.4,
    },
    {
        "grid_id": "IND-E-16",
        "name": "Odisha Coastal Cyclone Corridor (Paradip)",
        "subdivision": "Odisha Coastal",
        "lat": 20.31,
        "lon": 86.61,
        "climate_type": "Tropical Low Pressure Corridor",
        "baseline_slp": 1002.5,
        "base_pwat": 66.0,
        "param_gain": 14.0,
        "chaos_gain": 13.0,
        "orographic_gain": 0.50,
        "published_bust_freq_pct": 31.5,
        "worst_lead_day": 2,
        "peak_event": "Cyclone / Monsoon Depression (BoB)",
        "published_mae_mm": 61.2,
    },
    {
        "grid_id": "IND-M-17",
        "name": "Central Bay of Bengal Deep Ocean Buoy",
        "subdivision": "Bay of Bengal Marine",
        "lat": 15.00,
        "lon": 88.50,
        "climate_type": "Open Ocean Tropical Cyclogenesis",
        "baseline_slp": 1001.0,
        "base_pwat": 72.0,
        "param_gain": 13.0,
        "chaos_gain": 12.5,
        "orographic_gain": 0.10,
        "published_bust_freq_pct": 38.7,
        "worst_lead_day": 2,
        "peak_event": "Tropical Cyclogenesis (BoB)",
        "published_mae_mm": 84.3,
    },
    {
        "grid_id": "IND-M-18",
        "name": "Arabian Sea Deep Moored Array",
        "subdivision": "Arabian Sea Offshore",
        "lat": 16.50,
        "lon": 68.80,
        "climate_type": "Marine Somali Jet Confluence",
        "baseline_slp": 1005.0,
        "base_pwat": 59.0,
        "param_gain": 12.5,
        "chaos_gain": 12.0,
        "orographic_gain": 0.10,
        "published_bust_freq_pct": 29.4,
        "worst_lead_day": 3,
        "peak_event": "Arabian Sea Cyclone / Somali Jet Surge",
        "published_mae_mm": 52.1,
    },
    {
        "grid_id": "IND-S-19",
        "name": "Palk Strait Inter-Basin Channel (Kanyakumari)",
        "subdivision": "Southern Maritime Boundary",
        "lat": 8.08,
        "lon": 77.53,
        "climate_type": "Equatorial Ocean Gateway",
        "baseline_slp": 1009.8,
        "base_pwat": 52.0,
        "param_gain": 10.0,
        "chaos_gain": 9.5,
        "orographic_gain": 0.20,
        "published_bust_freq_pct": 13.6,
        "worst_lead_day": 5,
        "peak_event": "Equatorial Wave / ITCZ Disruption",
        "published_mae_mm": 21.3,
    },
    {
        "grid_id": "IND-N-20",
        "name": "Ladakh Cold Steppe & Trans-Himalayas (Leh)",
        "subdivision": "High Altitude Arid",
        "lat": 34.15,
        "lon": 77.57,
        "climate_type": "Polar / Alpine Desert",
        "baseline_slp": 1019.0,
        "base_pwat": 12.0,
        "param_gain": 5.0,
        "chaos_gain": 5.5,
        "orographic_gain": 0.70,
        "published_bust_freq_pct": 7.4,
        "worst_lead_day": 9,
        "peak_event": "Western Disturbance",
        "published_mae_mm": 8.9,
    },
]

REGION_BY_ID: Dict[str, Dict[str, Any]] = {r["grid_id"]: r for r in REGIONS}

DOMAIN_BOUNDS = {
    "lat_bounds": [settings.LAT_MIN, settings.LAT_MAX],
    "lon_bounds": [settings.LON_MIN, settings.LON_MAX],
    "total_stations": len(REGIONS),
}
